# CMake generated Testfile for 
# Source directory: F:/ARK Iris/Heart-Plugin/ark-plugin
# Build directory: F:/ARK Iris/Heart-Plugin/ark-plugin/build-http-policy
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DeliveryJournalTests "F:/ARK Iris/Heart-Plugin/ark-plugin/build-http-policy/Debug/DeliveryJournalTests.exe")
  set_tests_properties(DeliveryJournalTests PROPERTIES  _BACKTRACE_TRIPLES "F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;108;add_test;F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DeliveryJournalTests "F:/ARK Iris/Heart-Plugin/ark-plugin/build-http-policy/Release/DeliveryJournalTests.exe")
  set_tests_properties(DeliveryJournalTests PROPERTIES  _BACKTRACE_TRIPLES "F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;108;add_test;F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DeliveryJournalTests "F:/ARK Iris/Heart-Plugin/ark-plugin/build-http-policy/MinSizeRel/DeliveryJournalTests.exe")
  set_tests_properties(DeliveryJournalTests PROPERTIES  _BACKTRACE_TRIPLES "F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;108;add_test;F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DeliveryJournalTests "F:/ARK Iris/Heart-Plugin/ark-plugin/build-http-policy/RelWithDebInfo/DeliveryJournalTests.exe")
  set_tests_properties(DeliveryJournalTests PROPERTIES  _BACKTRACE_TRIPLES "F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;108;add_test;F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;0;")
else()
  add_test(DeliveryJournalTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(WalletNotificationsTests "F:/ARK Iris/Heart-Plugin/ark-plugin/build-http-policy/Debug/WalletNotificationsTests.exe")
  set_tests_properties(WalletNotificationsTests PROPERTIES  _BACKTRACE_TRIPLES "F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;122;add_test;F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(WalletNotificationsTests "F:/ARK Iris/Heart-Plugin/ark-plugin/build-http-policy/Release/WalletNotificationsTests.exe")
  set_tests_properties(WalletNotificationsTests PROPERTIES  _BACKTRACE_TRIPLES "F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;122;add_test;F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(WalletNotificationsTests "F:/ARK Iris/Heart-Plugin/ark-plugin/build-http-policy/MinSizeRel/WalletNotificationsTests.exe")
  set_tests_properties(WalletNotificationsTests PROPERTIES  _BACKTRACE_TRIPLES "F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;122;add_test;F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(WalletNotificationsTests "F:/ARK Iris/Heart-Plugin/ark-plugin/build-http-policy/RelWithDebInfo/WalletNotificationsTests.exe")
  set_tests_properties(WalletNotificationsTests PROPERTIES  _BACKTRACE_TRIPLES "F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;122;add_test;F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;0;")
else()
  add_test(WalletNotificationsTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(RequestPolicyTests "F:/ARK Iris/Heart-Plugin/ark-plugin/build-http-policy/Debug/RequestPolicyTests.exe")
  set_tests_properties(RequestPolicyTests PROPERTIES  _BACKTRACE_TRIPLES "F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;134;add_test;F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(RequestPolicyTests "F:/ARK Iris/Heart-Plugin/ark-plugin/build-http-policy/Release/RequestPolicyTests.exe")
  set_tests_properties(RequestPolicyTests PROPERTIES  _BACKTRACE_TRIPLES "F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;134;add_test;F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(RequestPolicyTests "F:/ARK Iris/Heart-Plugin/ark-plugin/build-http-policy/MinSizeRel/RequestPolicyTests.exe")
  set_tests_properties(RequestPolicyTests PROPERTIES  _BACKTRACE_TRIPLES "F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;134;add_test;F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(RequestPolicyTests "F:/ARK Iris/Heart-Plugin/ark-plugin/build-http-policy/RelWithDebInfo/RequestPolicyTests.exe")
  set_tests_properties(RequestPolicyTests PROPERTIES  _BACKTRACE_TRIPLES "F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;134;add_test;F:/ARK Iris/Heart-Plugin/ark-plugin/CMakeLists.txt;0;")
else()
  add_test(RequestPolicyTests NOT_AVAILABLE)
endif()
