# HeartShop SQL Injection Detection Filter

[Definition]
failregex = ^<HOST> .* ".*(\%%27|\'|\-\-|\%%23|#).*" .*$
            ^<HOST> .* ".*union.*select.*" .*$
            ^<HOST> .* ".*select.*from.*where.*" .*$
            ^<HOST> .* ".*insert.*into.*" .*$
            ^<HOST> .* ".*delete.*from.*" .*$
            ^<HOST> .* ".*drop.*table.*" .*$
            ^<HOST> .* ".*exec.*xp_.*" .*$
            ^<HOST> .* sql.*injection.*detected.*$

ignoreregex =
